name: Go

on:
  push:
    paths:
      - "go/**"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "go/**"
      - ".github/workflows/go.yml"
  workflow_dispatch: {}

defaults:
  run:
    working-directory: go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod

      - name: Test
        run: go test ./...
